Added loop around the cvs checkout. Repeat if failed, and leave if repeated too many times.
git-svn-id: svn+ssh://svn.code.sf.net/p/cmusphinx/code/trunk/sphinx4@2973 94700074-3cef-4d97-a70e-9c8c206c02f5

diff --git a/tests/regression/regressionTest b/tests/regression/regressionTest
--- a/tests/regression/regressionTest
+++ b/tests/regression/regressionTest
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # Copyright 1999-2002 Carnegie Mellon University.  
 # Portions Copyright 2002 Sun Microsystems, Inc.  
 # Portions Copyright 2002 Mitsubishi Electronic Research Laboratories.
@@ -35,8 +35,26 @@ mkdir -p $testDir
 
 cd $testDir
 
+# start loop to download code
+success=0;
+count=0;
+
+while ((!$success)); do
 # checkout the source
-scvs checkout sphinx4
+if scvs checkout sphinx4
+then
+success=1;
+else
+let count++;
+if (($count>50)); then
+# not successful, and we attempted it too many times. Clean up and leave.
+cd $originalDir
+rmdir $testDir
+exit $count;
+fi
+fi
+done
+
 cd sphinx4/tests/regression
 
 # make sure that the main test script is executable
